default:
  tags:
    - docker

stages:
  - test
  - build
  - deploy

variables:
  CONTAINER_BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

# test:
#   image: docker:20.10.16
#   stage: test
#   script:
#   - docker build --target test -t dadjokestest .

build:
  image: docker:20.10.16
  stage: build
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build --target deploy -t $CONTAINER_BUILD_IMAGE .
  - docker push $CONTAINER_BUILD_IMAGE

release:
  stage: deploy
  image: docker:20.10.16
  script:
  - docker pull $CONTAINER_BUILD_IMAGE
  - docker tag $CONTAINER_BUILD_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
  - main

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest
  script:
  - ecs update-task-definition
