USE [master]
GO
/****** Object:  Database [FanDev]    Script Date: 6/14/2023 6:38:23 PM ******/
CREATE DATABASE [FanDev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TT_Stats', FILENAME = N'C:\Users\brenn\TT_Stats.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TT_Stats_log', FILENAME = N'C:\Users\brenn\TT_Stats_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [FanDev] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FanDev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FanDev] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FanDev] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FanDev] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FanDev] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FanDev] SET ARITHABORT OFF 
GO
ALTER DATABASE [FanDev] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FanDev] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FanDev] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FanDev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FanDev] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FanDev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FanDev] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FanDev] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FanDev] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FanDev] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FanDev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FanDev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FanDev] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FanDev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FanDev] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FanDev] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FanDev] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FanDev] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FanDev] SET  MULTI_USER 
GO
ALTER DATABASE [FanDev] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FanDev] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FanDev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FanDev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FanDev] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FanDev] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FanDev] SET QUERY_STORE = OFF
GO
ALTER DATABASE [FanDev] SET READ_WRITE
GO