USE [master]
GO

/****** Object:  Database [FanDev]    Script Date: 1/13/2024 2:14:36 PM ******/
CREATE DATABASE [FanDev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FanDev', FILENAME = N'C:\Users\brenn\source\SQLS3\MSSQL16.SQLEXPRESS\MSSQL\DATA\FanDev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FanDev_log', FILENAME = N'C:\Users\brenn\source\SQLS3\MSSQL16.SQLEXPRESS\MSSQL\DATA\FanDev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FanDev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FanDev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FanDev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FanDev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FanDev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FanDev] SET ARITHABORT OFF 
GO

ALTER DATABASE [FanDev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FanDev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FanDev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FanDev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FanDev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FanDev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FanDev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FanDev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FanDev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FanDev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FanDev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FanDev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FanDev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FanDev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FanDev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FanDev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FanDev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FanDev] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FanDev] SET  MULTI_USER 
GO

ALTER DATABASE [FanDev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FanDev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FanDev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FanDev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FanDev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FanDev] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FanDev] SET QUERY_STORE = ON
GO

ALTER DATABASE [FanDev] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [FanDev] SET  READ_WRITE 
GO


